#servoy
#Thu Aug 27 18:50:35 EEST 2026
ApplicationServer.pingDelay=225
server.0.URL=jdbc\:hsqldb\:mem\:example_data
server.0.catalog=<none>
server.0.clientOnlyConnections=false
server.0.connectionValidationType=0
server.0.driver=org.hsqldb.jdbcDriver
server.0.enabled=true
server.0.maxConnectionsActive=5
server.0.maxConnectionsIdle=2
server.0.maxPreparedStatementsIdle=20
server.0.password=encrypted\:XAFg2JKIdj0\=
server.0.prefixTables=false
server.0.queryProcedures=false
server.0.schema=<none>
server.0.serverName=example_data
server.0.skipSysTables=true
server.0.userName=sa
servoy.developer.showStartPage=false
servoy.jwt.logintoken.password=encrypted\:lEncOF29lWnWEPPYb7fP5XGPuSs5smJrV76G3JtClaTG75F3RkhYqBWHMQit5RXq
servoy.ngclient.testingMode=true
servoy.ngclient.titanium.build.disabled=true
servoy.objectPoolSize=50000
