/*
 This file belongs to the Servoy development and deployment environment, Copyright (C) 2026 Servoy BV

 This program is free software; you can redistribute it and/or modify it under
 the terms of the GNU Affero General Public License as published by the Free
 Software Foundation; either version 3 of the License, or (at your option) any
 later version.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.

 You should have received a copy of the GNU Affero General Public License along
 with this program; if not, see http://www.gnu.org/licenses or write to the Free
 Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/
package com.servoy.eclipse.cypress.services;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import org.eclipse.e4.core.di.annotations.Creatable;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.servoy.eclipse.model.nature.ServoyProject;
import com.servoy.j2db.persistence.RepositoryException;
import com.servoy.j2db.persistence.Solution;

@Creatable
public class CypressLoginSupport {

	private static final String LOGIN_COMMAND_MARKER = "Cypress.Commands.add('login'";

	private static final String LOGIN_COMMAND_CONTENT = """
			// Auto-generated by Servoy MCP â€” reusable login using cy.session (cached per user).
			Cypress.Commands.add('login', (username, password) => {
			  username = username || Cypress.env('TEST_USERNAME');
			  password = password || Cypress.env('TEST_PASSWORD');
			  cy.session([username], () => {
			    cy.visit(Cypress.env('LOGIN_URL') || '/');
			    // Dismiss any blocking modals (cookie consent, timezone error, etc.)
			    // that may appear before the login form is interactable.
			    // eslint-disable-next-line cypress/no-unnecessary-waiting
			    cy.wait(500);
			    cy.get('body').then(($body) => {
			      // Click cookie consent button if present (data-cy pattern used by Servoy Cloud)
			      const $cookie = $body.find('[data-cy*="cookieConsent"] button, [data-cy*="cookieConsent"]').filter(':visible');
			      if ($cookie.length > 0) { cy.wrap($cookie.first()).click(); }
			      // Dismiss any other modal (e.g. timezone error) with an OK/Close button
			      const $modalBtn = $body.find('.modal.in button, .modal.show button').filter(function () {
			        return /^(OK|Close|Accept|Save)$/i.test(Cypress.$(this).text().trim());
			      });
			      if ($modalBtn.length > 0) { cy.wrap($modalBtn.first()).click(); }
			    });
			    cy.get('.modal-backdrop', { timeout: 5000 }).should('not.exist');
			    // Selectors are best-effort; adjust to match the solution's login form.
			    cy.get('input[name="username"], input[type="email"], #username').type(username);
			    cy.get('input[name="password"], input[type="password"], #password').type(password, { log: false });
			    cy.get('button[type="submit"], input[type="submit"], .login-button').click();
			    cy.get(Cypress.env('LOGIN_SUCCESS_SELECTOR') || 'body').should('exist');
			  });
			});
			""";

	private static final String CYPRESS_ENV_JSON = "cypress.env.json";
	private static final String GITIGNORE_FILE = ".gitignore";
	private static final ObjectMapper MAPPER = new ObjectMapper();

	public enum AuthKind {
		NONE, LOGIN_FORM, STATELESS, UNKNOWN
	}

	public record AuthRequirement(boolean required, AuthKind kind, String loginFormName, String loginSolutionName) {
	}

	/**
	 * Detects whether the active solution requires authentication by inspecting the
	 * solution's login form, login solution, and mustAuthenticate settings. A
	 * solution with {@code loginFormID != null && mustAuthenticate} is classified
	 * as LOGIN_FORM; one with only {@code mustAuthenticate} as STATELESS; otherwise
	 * NONE.
	 */
	public AuthRequirement detectAuth(ServoyProject servoyProject) {
		if (servoyProject == null || servoyProject.getEditingSolution() == null) {
			return new AuthRequirement(false, AuthKind.NONE, null, null);
		}

		Solution solution = servoyProject.getEditingSolution();

		String loginFormId = solution.getLoginFormID();
		boolean mustAuth = solution.getMustAuthenticate();

		String loginSolutionName = null;
		try {
			loginSolutionName = solution.getLoginSolutionName();
		} catch (RepositoryException e) {
			// ignore â€” treat as no login solution
		}

		if (loginFormId != null && mustAuth) {
			return new AuthRequirement(true, AuthKind.LOGIN_FORM, loginFormId, loginSolutionName);
		}

		if (loginSolutionName != null) {
			return new AuthRequirement(true, AuthKind.LOGIN_FORM, null, loginSolutionName);
		}

		if (mustAuth) {
			return new AuthRequirement(true, AuthKind.STATELESS, null, null);
		}

		return new AuthRequirement(false, AuthKind.NONE, null, null);
	}

	/**
	 * Writes the reusable {@code cy.login()} command to the appropriate commands
	 * file in the support directory. If {@code commands.ts} exists, writes there
	 * (TypeScript projects); otherwise writes to {@code commands.js}. Uses a marker
	 * check to ensure idempotency â€” returns {@code false} if already present in
	 * either file.
	 *
	 * @return {@code true} if the command was written, {@code false} if it already
	 *         existed
	 */
	public boolean writeLoginCommand(Path supportDir) throws IOException {
		Files.createDirectories(supportDir);

		// Determine the target file: prefer .ts if it exists, otherwise .js
		Path tsFile = supportDir.resolve("commands.ts");
		Path jsFile = supportDir.resolve("commands.js");
		Path commandsFile = Files.exists(tsFile) ? tsFile : jsFile;

		if (Files.exists(commandsFile)) {
			String existing = Files.readString(commandsFile, StandardCharsets.UTF_8);
			if (existing.contains(LOGIN_COMMAND_MARKER)) {
				return false;
			}
			// Also check the other file variant for idempotency
			Path otherFile = commandsFile.equals(tsFile) ? jsFile : tsFile;
			if (Files.exists(otherFile)) {
				String otherContent = Files.readString(otherFile, StandardCharsets.UTF_8);
				if (otherContent.contains(LOGIN_COMMAND_MARKER)) {
					return false;
				}
			}
			String updated = existing + "\n" + LOGIN_COMMAND_CONTENT;
			Files.writeString(commandsFile, updated, StandardCharsets.UTF_8);
		} else {
			Files.writeString(commandsFile, LOGIN_COMMAND_CONTENT, StandardCharsets.UTF_8);
		}
		return true;
	}

	/**
	 * Writes or merges login credentials into {@code cypress.env.json} in the given
	 * scripts directory. Existing keys are preserved; login-related keys are
	 * added/updated.
	 */
	public void writeCypressEnvJson(Path scriptsDir, String loginUrl, String username, String password,
			String loginSuccessSelector) throws IOException {
		Path envFile = scriptsDir.resolve(CYPRESS_ENV_JSON);

		ObjectNode root;
		if (Files.exists(envFile)) {
			root = (ObjectNode) MAPPER.readTree(Files.readString(envFile, StandardCharsets.UTF_8));
		} else {
			root = MAPPER.createObjectNode();
		}

		root.put("LOGIN_URL", loginUrl);
		root.put("TEST_USERNAME", username);
		root.put("TEST_PASSWORD", password);
		root.put("LOGIN_SUCCESS_SELECTOR", loginSuccessSelector);

		Files.writeString(envFile, MAPPER.writerWithDefaultPrettyPrinter().writeValueAsString(root),
				StandardCharsets.UTF_8);
	}

	/**
	 * Ensures {@code cypress.env.json} is listed in the {@code .gitignore} file of
	 * the scripts directory. Creates the file if absent; appends if not already
	 * present.
	 */
	public void ensureGitignoreEntry(Path scriptsDir) throws IOException {
		Path gitignoreFile = scriptsDir.resolve(GITIGNORE_FILE);

		if (Files.exists(gitignoreFile)) {
			List<String> lines = Files.readAllLines(gitignoreFile, StandardCharsets.UTF_8);
			for (String line : lines) {
				if (line.trim().equals(CYPRESS_ENV_JSON)) {
					return;
				}
			}
			String content = Files.readString(gitignoreFile, StandardCharsets.UTF_8);
			if (!content.endsWith("\n")) {
				content += "\n";
			}
			content += CYPRESS_ENV_JSON + "\n";
			Files.writeString(gitignoreFile, content, StandardCharsets.UTF_8);
		} else {
			Files.writeString(gitignoreFile, CYPRESS_ENV_JSON + "\n", StandardCharsets.UTF_8);
		}
	}

	/**
	 * Builds a human-readable message telling the MCP agent that this solution
	 * requires login credentials and should re-invoke with the necessary
	 * parameters.
	 */
	public String buildAuthRequiredMessage(AuthRequirement auth) {
		StringBuilder sb = new StringBuilder();
		sb.append("This solution requires login (");
		sb.append(auth.kind());
		if (auth.loginFormName() != null) {
			sb.append(": '").append(auth.loginFormName()).append("'");
		} else if (auth.loginSolutionName() != null) {
			sb.append(": login solution '").append(auth.loginSolutionName()).append("'");
		}
		sb.append("). Re-run generateCypressE2ETest with loginUrl, testUsername, testPassword, ");
		sb.append("and loginSuccessSelector so I can generate a reusable login step. ");
		sb.append("Credentials will be written to a gitignored cypress.env.json, not into the test files.");
		return sb.toString();
	}
}

